
package com.example.service.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UpdateService", targetNamespace = "http://service.service.example.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UpdateService {


    /**
     * 
     * @param parameters
     * @return
     *     returns java.lang.Object
     */
    @WebMethod
    @WebResult(name = "getPatchResponse", targetNamespace = "http://service.service.example.com/", partName = "parameters")
    public GetPatchResponse getPatch(
        @WebParam(name = "getPatch", targetNamespace = "http://service.service.example.com/", partName = "parameters")
        GetPatch parameters);

}
